In [42]:
import numpy as np
import pandas as pd

In [52]:
# EXERCICIO - 01
# Crie um array NumPy com 1000000 e uma lista com 1000000.
# Multiplique cada elemento do array e da lista por 2 e calcule o tempo de execução com cada um dos objetos (use %time).
# Qual objeto oferece melhor performance, array NumPy ou lista?

a = np.arange(100)
print('a = ', a)

l = [x for x in range(100)]
print('b = ', l)

a =  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
b =  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]


In [58]:
# EXRRCICIO - 02
# Crie um array de 10 elementos
# Altere o valores de todos os elementos dos índices 5 a 8 para 0

# criando o array
a = np.arange(10)
print(a)

# alterando os valores dos indices de 5 a 8
a[5:9] = 0
print(a)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 0 0 0 0 9]


In [62]:
# EXERCICIO - 03
# Crie um array de 3 dimensões e imprima a dimensão 1

a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

a[1]

array([4, 5, 6])

In [88]:
# EXERCICIO - 04
# Crie um array de duas dimensões (matriz).
# Imprima os elementos da terceira linha da matriz
# Imprima todos os elementos da primeira e segunda linhas e segunda e terceira colunas

#Criando a matriz
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print('Matriz\n',matrix)

print('Elementos Terceira linha\n',matrix[2])

print('Elementos da primeira e segundas linhas\n', matrix[0:2], '\nE segunda e terceira coluna\n', matrix.transpose()[1:3])

Matriz
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Elementos Terceira linha
 [7 8 9]
Elementos da primeira e segundas linhas
 [[1 2 3]
 [4 5 6]] 
E segunda e terceira coluna
 [[2 5 8]
 [3 6 9]]


In [96]:
# EXERCICIO - 05
# Calcule a transposta da matriz abaixo
arr = np.arange(15).reshape((3, 5))
print('Matrix Original\n',arr)

#matrix transposta de arr
arr1 = arr.transpose()
print('Matrix Transposta\n',arr1)

Matrix Original
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
Matrix Transposta
 [[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [170]:
# EXERCICIO - 06
# Considere os 3 arrays abaixo
# Retorne o valor do array xarr se o valor for True no array cond. Caso contrário, retorne o valor do array yarr.

i = 0
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])
new = np.arange(float(len(xarr)))

for x in cond:
    if x:
        new[i] = xarr[i]
    else:
        new[i] = yarr[i]
    i += 1

print(new)

[1.1 2.2 1.3 1.4 2.5]


In [176]:
# EXERCICIO - 07
# Crie um array A com 10 elementos e salve o array em disco com a extensão npy
# Depois carregue o array do disco no array B

#Gera array com 10 posições 
a = np.arange(10)

# salva o array no arquivo array.npy
np.save('array.npy', a)

# cria array b com os dados do arquvio array.npy
b = np.load('array.npy')

print(b)

[0 1 2 3 4 5 6 7 8 9]


In [180]:
# EXERCICIO - 08
# Considerando a série abaixo, imprima os valores únicos na série
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c', 'a', 'b'])

#imprimindo os valores unicos
obj.unique()

array(['c', 'a', 'd', 'b'], dtype=object)

In [195]:
# EXERCICIO - 09
# Considerando o trecho de código que conecta em uma url na internet, imprima o dataframe conforme abaixo.
import requests
url = 'https://api.github.com/repos/pandas-dev/pandas/issues'
resp = requests.get(url)

df = pd.DataFrame(resp.json(), columns = ['number', 'title', 'labels', 'state'])

df

number  ... state
0    34265  ...  open
1    34264  ...  open
2    34263  ...  open
3    34262  ...  open
4    34261  ...  open
5    34259  ...  open
6    34258  ...  open
7    34257  ...  open
8    34256  ...  open
9    34255  ...  open
10   34254  ...  open
11   34253  ...  open
12   34252  ...  open
13   34251  ...  open
14   34249  ...  open
15   34248  ...  open
16   34244  ...  open
17   34243  ...  open
18   34241  ...  open
19   34240  ...  open
20   34238  ...  open
21   34237  ...  open
22   34236  ...  open
23   34235  ...  open
24   34233  ...  open
25   34231  ...  open
26   34229  ...  open
27   34228  ...  open
28   34226  ...  open
29   34225  ...  open

[30 rows x 4 columns]

In [ ]:
# EXERCICIO - 10
# Crie um banco de dados no SQLite, crie uma tabela, insira registros, 
# consulte a tabela e retorne os dados em dataframe do Pandas

In [205]:
import os
import sqlite3

con = sqlite3.connect('empresa.db')
cur = con.cursor()

# criando instrução Sql
#sql_create = 'create table funcionario '\
#'(id integer primary key,'\
#'nome varchar(100),'\
#'cargo varchar(140),'\
#'salario float)'\

#cur.execute(sql_create)

#dados
#recfuncionario = [(1000, 'Guilherme Roncato', 'Presidente', 150000.00),
#                  (1001, 'Alexandra Maria', 'Vice Presidente', 125500.00),
#                  (1002, 'Joana Roncato', 'Diretor', 95000.00)]

#sql_insert = 'insert into funcionario values(?, ?, ?, ?)'
#inserindo os registros
#for rec in recfuncionario:
#    cur.execute(sql_insert, rec)
#con.commit()


# consultando os dados
sql_select = 'select * from funcionario'

cur.execute(sql_select)
dados = cur.fetchall()

df = pd.DataFrame(dados, columns = ['id','nome', 'cargo', 'salario'])

con.close()

df


id               nome            cargo   salario
0  1000  Guilherme Roncato       Presidente  150000.0
1  1001    Alexandra Maria  Vice Presidente  125500.0
2  1002      Joana Roncato          Diretor   95000.0